use hell_input::{KeyCode, KeyState};

pub(crate) fn keycode_to_hell(k: &winit::event::VirtualKeyCode) -> KeyCode {
    match k{
        winit::event::VirtualKeyCode::Key1 => KeyCode::Alpha1,
        winit::event::VirtualKeyCode::Key2 => KeyCode::Alpha2,
        winit::event::VirtualKeyCode::Key3 => KeyCode::Alpha3,
        winit::event::VirtualKeyCode::Key4 => KeyCode::Alpha4,
        winit::event::VirtualKeyCode::Key5 => KeyCode::Alpha5,
        winit::event::VirtualKeyCode::Key6 => KeyCode::Alpha6,
        winit::event::VirtualKeyCode::Key7 => KeyCode::Alpha7,
        winit::event::VirtualKeyCode::Key8 => KeyCode::Alpha8,
        winit::event::VirtualKeyCode::Key9 => KeyCode::Alpha9,
        winit::event::VirtualKeyCode::Key0 => KeyCode::Alpha0,
        winit::event::VirtualKeyCode::A => KeyCode::A,
        winit::event::VirtualKeyCode::B => KeyCode::B,
        winit::event::VirtualKeyCode::C => KeyCode::C,
        winit::event::VirtualKeyCode::D => KeyCode::D,
        winit::event::VirtualKeyCode::E => KeyCode::E,
        winit::event::VirtualKeyCode::F => KeyCode::F,
        winit::event::VirtualKeyCode::G => KeyCode::G,
        winit::event::VirtualKeyCode::H => KeyCode::H,
        winit::event::VirtualKeyCode::I => KeyCode::I,
        winit::event::VirtualKeyCode::J => KeyCode::J,
        winit::event::VirtualKeyCode::K => KeyCode::K,
        winit::event::VirtualKeyCode::L => KeyCode::L,
        winit::event::VirtualKeyCode::M => KeyCode::M,
        winit::event::VirtualKeyCode::N => KeyCode::N,
        winit::event::VirtualKeyCode::O => KeyCode::O,
        winit::event::VirtualKeyCode::P => KeyCode::P,
        winit::event::VirtualKeyCode::Q => KeyCode::Q,
        winit::event::VirtualKeyCode::R => KeyCode::R,
        winit::event::VirtualKeyCode::S => KeyCode::S,
        winit::event::VirtualKeyCode::T => KeyCode::T,
        winit::event::VirtualKeyCode::U => KeyCode::U,
        winit::event::VirtualKeyCode::V => KeyCode::V,
        winit::event::VirtualKeyCode::W => KeyCode::W,
        winit::event::VirtualKeyCode::X => KeyCode::X,
        winit::event::VirtualKeyCode::Y => KeyCode::Y,
        winit::event::VirtualKeyCode::Z => KeyCode::Z,
        winit::event::VirtualKeyCode::Escape => KeyCode::Escape,
        winit::event::VirtualKeyCode::F1 => KeyCode::F1,
        winit::event::VirtualKeyCode::F2 => KeyCode::F2,
        winit::event::VirtualKeyCode::F3 => KeyCode::F3,
        winit::event::VirtualKeyCode::F4 => KeyCode::F4,
        winit::event::VirtualKeyCode::F5 => KeyCode::F5,
        winit::event::VirtualKeyCode::F6 => KeyCode::F6,
        winit::event::VirtualKeyCode::F7 => KeyCode::F7,
        winit::event::VirtualKeyCode::F8 => KeyCode::F8,
        winit::event::VirtualKeyCode::F9 => KeyCode::F9,
        winit::event::VirtualKeyCode::F10 => KeyCode::F10,
        winit::event::VirtualKeyCode::F11 => KeyCode::F11,
        winit::event::VirtualKeyCode::F12 => KeyCode::F12,
        winit::event::VirtualKeyCode::F13 => KeyCode::F13,
        winit::event::VirtualKeyCode::F14 => KeyCode::F14,
        winit::event::VirtualKeyCode::F15 => KeyCode::F15,
        winit::event::VirtualKeyCode::F16 => KeyCode::F16,
        winit::event::VirtualKeyCode::F17 => KeyCode::F17,
        winit::event::VirtualKeyCode::F18 => KeyCode::F18,
        winit::event::VirtualKeyCode::F19 => KeyCode::F19,
        winit::event::VirtualKeyCode::F20 => KeyCode::F20,
        winit::event::VirtualKeyCode::F21 => KeyCode::F21,
        winit::event::VirtualKeyCode::F22 => KeyCode::F22,
        winit::event::VirtualKeyCode::F23 => KeyCode::F23,
        winit::event::VirtualKeyCode::F24 => KeyCode::F24,
        winit::event::VirtualKeyCode::Snapshot => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Scroll => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Pause => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Insert => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Home => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Delete => KeyCode::Invalid,
        winit::event::VirtualKeyCode::End => KeyCode::Invalid,
        winit::event::VirtualKeyCode::PageDown => KeyCode::Invalid,
        winit::event::VirtualKeyCode::PageUp => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Left => KeyCode::ArrowLeft,
        winit::event::VirtualKeyCode::Up => KeyCode::ArrowUp,
        winit::event::VirtualKeyCode::Right => KeyCode::ArrowRight,
        winit::event::VirtualKeyCode::Down => KeyCode::ArrowDown,
        winit::event::VirtualKeyCode::Back => KeyCode::Backspace,
        winit::event::VirtualKeyCode::Return => KeyCode::Return,
        winit::event::VirtualKeyCode::Space => KeyCode::Space,
        winit::event::VirtualKeyCode::Compose => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Caret => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Numlock => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Numpad0 => KeyCode::Numpad0,
        winit::event::VirtualKeyCode::Numpad1 => KeyCode::Numpad1,
        winit::event::VirtualKeyCode::Numpad2 => KeyCode::Numpad2,
        winit::event::VirtualKeyCode::Numpad3 => KeyCode::Numpad3,
        winit::event::VirtualKeyCode::Numpad4 => KeyCode::Numpad4,
        winit::event::VirtualKeyCode::Numpad5 => KeyCode::Numpad5,
        winit::event::VirtualKeyCode::Numpad6 => KeyCode::Numpad6,
        winit::event::VirtualKeyCode::Numpad7 => KeyCode::Numpad7,
        winit::event::VirtualKeyCode::Numpad8 => KeyCode::Numpad8,
        winit::event::VirtualKeyCode::Numpad9 => KeyCode::Numpad9,
        winit::event::VirtualKeyCode::NumpadAdd => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NumpadDivide => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NumpadDecimal => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NumpadComma => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NumpadEnter => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NumpadEquals => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NumpadMultiply => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NumpadSubtract => KeyCode::Invalid,
        winit::event::VirtualKeyCode::AbntC1 => KeyCode::Invalid,
        winit::event::VirtualKeyCode::AbntC2 => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Apostrophe => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Apps => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Asterisk => KeyCode::Invalid,
        winit::event::VirtualKeyCode::At => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Ax => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Backslash => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Calculator => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Capital => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Colon => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Comma => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Convert => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Equals => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Grave => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Kana => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Kanji => KeyCode::Invalid,
        winit::event::VirtualKeyCode::LAlt => KeyCode::AltLeft,
        winit::event::VirtualKeyCode::LBracket => KeyCode::Invalid,
        winit::event::VirtualKeyCode::LControl => KeyCode::ControlLeft,
        winit::event::VirtualKeyCode::LShift => KeyCode::ShiftLeft,
        winit::event::VirtualKeyCode::LWin => KeyCode::MetaLeft,
        winit::event::VirtualKeyCode::Mail => KeyCode::Invalid,
        winit::event::VirtualKeyCode::MediaSelect => KeyCode::Invalid,
        winit::event::VirtualKeyCode::MediaStop => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Minus => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Mute => KeyCode::Invalid,
        winit::event::VirtualKeyCode::MyComputer => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NavigateForward => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NavigateBackward => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NextTrack => KeyCode::Invalid,
        winit::event::VirtualKeyCode::NoConvert => KeyCode::Invalid,
        winit::event::VirtualKeyCode::OEM102 => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Period => KeyCode::Invalid,
        winit::event::VirtualKeyCode::PlayPause => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Plus => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Power => KeyCode::Invalid,
        winit::event::VirtualKeyCode::PrevTrack => KeyCode::Invalid,
        winit::event::VirtualKeyCode::RAlt => KeyCode::AltRight,
        winit::event::VirtualKeyCode::RBracket => KeyCode::Invalid,
        winit::event::VirtualKeyCode::RControl => KeyCode::ControlRight,
        winit::event::VirtualKeyCode::RShift => KeyCode::ShiftRight,
        winit::event::VirtualKeyCode::RWin => KeyCode::MetaRight,
        winit::event::VirtualKeyCode::Semicolon => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Slash => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Sleep => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Stop => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Sysrq => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Tab => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Underline => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Unlabeled => KeyCode::Invalid,
        winit::event::VirtualKeyCode::VolumeDown => KeyCode::Invalid,
        winit::event::VirtualKeyCode::VolumeUp => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Wake => KeyCode::Invalid,
        winit::event::VirtualKeyCode::WebBack => KeyCode::Invalid,
        winit::event::VirtualKeyCode::WebFavorites => KeyCode::Invalid,
        winit::event::VirtualKeyCode::WebForward => KeyCode::Invalid,
        winit::event::VirtualKeyCode::WebHome => KeyCode::Invalid,
        winit::event::VirtualKeyCode::WebRefresh => KeyCode::Invalid,
        winit::event::VirtualKeyCode::WebSearch => KeyCode::Invalid,
        winit::event::VirtualKeyCode::WebStop => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Yen => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Copy => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Paste => KeyCode::Invalid,
        winit::event::VirtualKeyCode::Cut => KeyCode::Invalid,
    }
}

pub fn element_state_to_hell(state: winit::event::ElementState) -> KeyState {
    match state {
        winit::event::ElementState::Pressed => KeyState::Pressed,
        winit::event::ElementState::Released => KeyState::Released,
    }
}


// pub(crate) fn update_key_state_winit(&mut self, e: winit::event::KeyboardInput) -> HellResult<()> {
//     if let Some(code) = e.virtual_keycode {
//         let keycode = KeyCode::from(code);
//         let state = self.key_states.get_mut(keycode as usize).unwrap();
//         *state = KeyState::from(e.state);
//     };
//
//     Ok(())
// }
